### ISSUE TITLE
When clients are in an Idle group and one client's preferred stream starts, both clients play it

### ISSUE THREAD

**Issue by markferry** [ahayworth/snapcast-autoconfig#4]
**os:** Arch linux
**snapclient:** 0.25.0
**snapserver:** 0.25.0

First off, I realise this is a side-effect of how Snapcast works when removing clients from groups ;)

In this scenario:
 *  there are two clients `c1` and `c2`
 * each client has its own preferred stream (`s1`, `s2`)
 * a "party" stream `s0` is lower priority and plays to both `s1` and `s2`

To repro:
 * Play `s0` such that `c1` and `c2` form a playing group `g0`.
 * Pause `s0`   ->  `c1` and `c2` remain in `g0` which is Idle
 * Play `s1`  -> the group splits

Result:
 * `c1` is in group `g1` playing `s1`
 * `c2` is in group `g2` playing `s1`  <-- DOH!
 
Expected:
 * `c2` remains in group `g0` which is Idle

Config:

```yaml
---
server: tcp://localhost:1705
streams:
  Canard:
    clients:
      - canard
  Kitchen:
    clients:
      - kitchen
  Party 1:
    clients:
      - canard
      - kitchen
```

The result is the same even with more clients in `g0`. All clients end up in individual groups playing `s1`.
[log.txt](https://github.com/ahayworth/snapcast-autoconfig/files/6909519/log.txt)
